### ISSUE TITLE
Would love to share your content with the word-by-word

### ISSUE THREAD

**Issue by mmahalwy** [oazabir/QuranApp#36]
Salam Omar, 

This is awesome mashallah!!! We should combine forces and help us out with Quran.com https://github.com/quran/quran.com-frontend we can definitely use your talent! 

Wanted to ask you for a small favor. We are providing an API and currently have word-by-word translation but missing transliteration. Would you mind sharing your content and/or leading us to where you gathered the word-by-word transliteration? We can definitely find huge use for it and the Muslim Ummah in general.

Thank you!

**Comment by oazabir** [comment]
Wassalam, I took the transliteration from the data file provided by the Corpus project. 

http://corpus.quran.com/download/

**Comment by mmahalwy** [comment]
@oazabir ah yes, that's one of our projects, but it seems that you organized it already? Do you have a db dump ?

**Comment by oazabir** [comment]
Here it is:

https://raw.githubusercontent.com/oazabir/QuranApp/master/data/Transliteration.csv

**Comment by oazabir** [comment]
Also if you can restore the database inside the data/ folder in SQL Server 2014 express, you will find a wealth of data already properly normailzed.

**Comment by mmahalwy** [comment]
oh wow @oazabir thanks for the CSV!!!

**Comment by mmahalwy** [comment]
@oazabir salam, so I started working with the CSV and found mistakes. Firstly, it's short of ~20,000 words. In addition you can see here:

```
49,18,5,l-samāwāti
49,18,6,wal-arḍi
49,18,7,wal-lahu
49,18,8,baṣīrun
49,18,10,taʿmalūna
50,1,2,wal-qur'āni
50,1,3,l-majīdi
50,2,2,ʿajibū
50,2,4,jāahum
50,2,5,mundhirun
50,2,7,faqāla
50,2,8,l-kāfirūna
50,2,10,shayon
50,2,11,ʿajībun
50,3,1,a-idhā
```

That the positions are not complete. It skips a few words here and there. Do you have an updated one?

**Comment by oazabir** [comment]
Looks like all the prepositions like bima, bal, and some nouns like hadha
is mssing. Most likely it wasn't in the original source from which I have
imported. Thus it is not there in my database either.

On Fri, Nov 20, 2015 at 10:53 AM, Mohamed El Mahallawy <
notifications@github.com> wrote:

> @oazabir https://github.com/oazabir salam, so I started working with
> the CSV and found mistakes. Firstly, it's short of ~20,000 words. In
> addition you can see here:
> 
> 49,18,5,l-samāwāti
> 49,18,6,wal-arḍi
> 49,18,7,wal-lahu
> 49,18,8,baṣīrun
> 49,18,10,taʿmalūna
> 50,1,2,wal-qur'āni
> 50,1,3,l-majīdi
> 50,2,2,ʿajibū
> 50,2,4,jāahum
> 50,2,5,mundhirun
> 50,2,7,faqāla
> 50,2,8,l-kāfirūna
> 50,2,10,shayon
> 50,2,11,ʿajībun
> 50,3,1,a-idhā
> 
> That the positions are not complete. It skips a few words here and there.
> Do you have an updated one?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/oazabir/QuranApp/issues/36#issuecomment-158357697.

## 

OmarALZabir.com/Charity

**Comment by mmahalwy** [comment]
do you have the original source? I can try to parse it or take a look at it too
